#!/usr/bin/env bash
#*******************************************************************************
# Copyright (c) 2024 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html
# SPDX-License-Identifier: EPL-2.0
#*******************************************************************************
# // Some portions generated by Co-Pilot

# Script to test API tokens for various services
# Usage: ./api-token.sh PROJECT_NAME SERVICE [TOKEN_NAME]

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"

usage() {
  cat <<EOF
Usage: ${SCRIPT_NAME} PROJECT_NAME SERVICE [TOKEN_NAME]

Test API tokens stored in Vault for various services.

Arguments:
  PROJECT_NAME    Project name (e.g., ee4j.mojarra)
  SERVICE         Service name. Supported services:
                    - github.com
                    - gitlab.eclipse.org
                    - sonarcloud.io
                    - test.pypi.org
                    - docker.com
                    - sbom.eclipse.org
                    - npmjs.com
                    - crates.io
  TOKEN_NAME      Custom token name (optional, default: api-token)

Examples:
  ${SCRIPT_NAME} ee4j.mojarra github.com
  ${SCRIPT_NAME} ee4j.mojarra gitlab.eclipse.org custom-token
EOF
}

# Parse positional arguments
if [[ $# -lt 2 ]]; then
  echo "Error: Missing required arguments" >&2
  usage
  exit 1
fi

PROJECT_NAME="${1}"
SERVICE="${2}"
TOKEN_NAME="${3:-api-token}"  # Default to "api-token" if not provided

# Validate required arguments
if [[ -z "${PROJECT_NAME}" ]]; then
  echo "Error: PROJECT_NAME is required" >&2
  usage
  exit 1
fi

if [[ -z "${SERVICE}" ]]; then
  echo "Error: SERVICE is required" >&2
  usage
  exit 1
fi

# Check Vault authentication status
echo "Checking Vault authentication..."
if ! vaultctl status &>/dev/null; then
  echo "⚠ Not authenticated to Vault. Logging in..."
  if ! vaultctl login; then
    echo "Error: Failed to authenticate to Vault" >&2
    exit 1
  fi
  echo "✓ Vault authentication successful"
else
  echo "✓ Vault authentication OK"
fi
echo ""

# Construct vault path based on service
VAULT_PATH="${PROJECT_NAME}/${SERVICE}/${TOKEN_NAME}"

echo "=========================================="
echo "Testing API token for ${SERVICE}"
echo "=========================================="
echo "Project: ${PROJECT_NAME}"
echo "Vault path: ${VAULT_PATH}"
echo ""

# Retrieve token from Vault
echo "Retrieving token from Vault..."
TOKEN=$(vaultctl read "cbi" "${VAULT_PATH}" 2>/dev/null || true)

if [[ -z "${TOKEN}" ]]; then
  echo "Error: Failed to retrieve token from Vault path: ${VAULT_PATH}" >&2
  exit 1
fi

echo "Token retrieved successfully (length: ${#TOKEN} characters)"
echo ""

# Test token based on service
test_github() {
  echo "Testing GitHub token..."
  RESPONSE=$(curl -s -w "\n%{http_code}" -H "Authorization: token ${TOKEN}" \
    "https://api.github.com/user")
  
  HTTP_CODE=$(echo "${RESPONSE}" | tail -n1)
  BODY=$(echo "${RESPONSE}" | sed '$d')
  
  if [[ "${HTTP_CODE}" == "200" ]]; then
    USERNAME=$(echo "${BODY}" | grep -o '"login": "[^"]*"' | cut -d'"' -f4)
    echo "✓ GitHub token is valid"
    echo "  Username: ${USERNAME}"
    return 0
  else
    echo "✗ GitHub token is invalid (HTTP ${HTTP_CODE})"
    echo "  Response: ${BODY}"
    return 1
  fi
}

test_gitlab() {
  echo "Testing GitLab token..."
  RESPONSE=$(curl -s -w "\n%{http_code}" -H "PRIVATE-TOKEN: ${TOKEN}" \
    "https://gitlab.eclipse.org/api/v4/user")
  
  HTTP_CODE=$(echo "${RESPONSE}" | tail -n1)
  BODY=$(echo "${RESPONSE}" | sed '$d')
  
  if [[ "${HTTP_CODE}" == "200" ]]; then
    USERNAME=$(echo "${BODY}" | grep -o '"username":"[^"]*"' | cut -d'"' -f4)
    echo "✓ GitLab token is valid"
    echo "  Username: ${USERNAME}"
    return 0
  else
    echo "✗ GitLab token is invalid (HTTP ${HTTP_CODE})"
    echo "  Response: ${BODY}"
    return 1
  fi
}

test_sonarcloud() {
  echo "Testing SonarCloud token..."
  RESPONSE=$(curl -s -w "\n%{http_code}" -u "${TOKEN}:" \
    "https://sonarcloud.io/api/authentication/validate")
  
  HTTP_CODE=$(echo "${RESPONSE}" | tail -n1)
  BODY=$(echo "${RESPONSE}" | sed '$d')
  
  if [[ "${HTTP_CODE}" == "200" ]] && echo "${BODY}" | grep -q '"valid":true'; then
    echo "✓ SonarCloud token is valid"
    echo "  Response: ${BODY}"
    return 0
  else
    echo "✗ SonarCloud token is invalid (HTTP ${HTTP_CODE})"
    echo "  Response: ${BODY}"
    return 1
  fi
}

test_docker() {
  echo "Testing Docker Hub token..."
  
  # Retrieve username from Vault
  echo "Retrieving Docker Hub username from Vault..."
  USERNAME=$(vaultctl read "cbi" "${PROJECT_NAME}/docker.com/username" 2>/dev/null || true)
  
  if [[ -z "${USERNAME}" ]]; then
    echo "ERROR: Could not retrieve username from Vault path: ${PROJECT_NAME}/docker.com/username"
    return 1
  fi
  
  echo "  Username: ${USERNAME}"
  echo ""
  
  # Test authentication with Docker Hub API
  echo "Testing Docker Hub authentication..."
  RESPONSE=$(curl -s -w "\n%{http_code}" \
    -H "Content-Type: application/json" \
    -d "{\"username\":\"${USERNAME}\",\"password\":\"${TOKEN}\"}" \
    "https://hub.docker.com/v2/users/login/")
  
  HTTP_CODE=$(echo "${RESPONSE}" | tail -n1)
  BODY=$(echo "${RESPONSE}" | sed '$d')
  
  if [[ "${HTTP_CODE}" == "200" ]]; then
    echo "✓ Docker Hub token is valid"
    echo "  Username: ${USERNAME}"
    return 0
  else
    echo "✗ Docker Hub token is invalid (HTTP ${HTTP_CODE})"
    echo "  Username: ${USERNAME}"
    echo "  Response: ${BODY}"
    return 1
  fi
}

test_sbom() {
  echo "Testing SBOM (Dependency-Track) token..."
  RESPONSE=$(curl -s -w "\n%{http_code}" \
    -H "X-Api-Key: ${TOKEN}" \
    "https://sbom.eclipse.org/api/version")
  
  HTTP_CODE=$(echo "${RESPONSE}" | tail -n1)
  BODY=$(echo "${RESPONSE}" | sed '$d')
  
  if [[ "${HTTP_CODE}" == "200" ]]; then
    echo "✓ SBOM (Dependency-Track) token is valid"
    return 0
  else
    echo "✗ SBOM (Dependency-Track) token is invalid (HTTP ${HTTP_CODE})"
    echo "  Response: ${BODY}"
    return 1
  fi
}

test_npmjs() {
  echo "Testing npmjs token..."
  
  RESPONSE=$(curl -s -w "\n%{http_code}" \
    -H "Authorization: Bearer ${TOKEN}" \
    "https://registry.npmjs.org/-/whoami")
  
  HTTP_CODE=$(echo "${RESPONSE}" | tail -n1)
  BODY=$(echo "${RESPONSE}" | sed '$d')
  
  if [[ "${HTTP_CODE}" == "200" ]]; then
    USERNAME=$(echo "${BODY}" | grep -o '"username":"[^"]*"' | cut -d'"' -f4)
    echo "✓ npmjs token is valid"
    echo "  Username: ${USERNAME}"
    return 0
  else
    echo "✗ npmjs token is invalid (HTTP ${HTTP_CODE})"
    echo "  Response: ${BODY}"
    return 1
  fi
}

test_crates() {
  echo "Testing crates.io token..."
  
  # Check if cargo is available
  if ! command -v cargo &> /dev/null; then
    echo "⚠ cargo command not found"
    echo "  Cannot validate crates.io token without cargo installed."
    echo "  Token length: ${#TOKEN} characters"
    return 0
  fi
  
  # Create temporary cargo home to avoid overwriting existing credentials
  TEMP_CARGO_HOME=$(mktemp -d)
  export CARGO_HOME="${TEMP_CARGO_HOME}"
  
  echo "Testing token with cargo login..."
  
  # Try to login with the token
  if echo "${TOKEN}" | cargo login --registry crates-io 2>&1 | tee /tmp/cargo_login.log | grep -q "Login token for"; then
    echo "✓ crates.io token is valid"
    echo "  Token successfully accepted by cargo"
    RESULT=0
  else
    # Check for specific error messages
    if grep -q "please visit https://crates.io/me" /tmp/cargo_login.log; then
      echo "✗ crates.io token is invalid"
      echo "  cargo rejected the token"
      RESULT=1
    elif grep -q "token is not valid" /tmp/cargo_login.log; then
      echo "✗ crates.io token is invalid"
      echo "  cargo reported: token is not valid"
      RESULT=1
    else
      echo "⚠ Unable to validate crates.io token"
      echo "  cargo login output:"
      cat /tmp/cargo_login.log | sed 's/^/    /'
      RESULT=0
    fi
  fi
  
  # Cleanup
  rm -f /tmp/cargo_login.log
  rm -rf "${TEMP_CARGO_HOME}"
  unset CARGO_HOME
  
  return ${RESULT}
}

# Route to appropriate test function
case "${SERVICE}" in
  github.com*)
    test_github
    ;;
  gitlab.eclipse.org*)
    test_gitlab
    ;;
  sonarcloud.io*)
    test_sonarcloud
    ;;
  docker.com*)
    test_docker
    ;;
  sbom.eclipse.org*)
    test_sbom
    ;;
  npmjs.com*)
    test_npmjs
    ;;
  crates.io*)
    test_crates
    ;;
  *)
    echo "Error: Unsupported service '${SERVICE}'" >&2
    echo "Supported services: github, gitlab, sonarcloud, docker, sbom, npmjs, crates" >&2
    exit 1
    ;;
esac

TEST_RESULT=$?

echo ""
echo "=========================================="
if [[ ${TEST_RESULT} -eq 0 ]]; then
  echo "✓ Token test PASSED"
else
  echo "✗ Token test FAILED"
fi
echo "=========================================="

exit ${TEST_RESULT}
