#!/usr/bin/env bash
#*******************************************************************************
# Copyright (c) 2026 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html
# SPDX-License-Identifier: EPL-2.0
#*******************************************************************************
# // Some portions generated by Co-Pilot

# ci-adm - Eclipse Common Build Infrastructure Administration CLI
# Main entry point for CBI admin tools

set -o errexit
set -o nounset
set -o pipefail

# Get the directory where this script is located (follow symlinks)
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$SCRIPT_DIR/$SOURCE" # if $SOURCE was a relative symlink, resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print functions
print_error() {
  printf "${RED}Error: %s${NC}\n" "$*" >&2
}

print_success() {
  printf "${GREEN}✓ %s${NC}\n" "$*"
}

print_info() {
  printf "${BLUE} %s${NC}\n" "$*"
}

print_warning() {
  printf "${YELLOW}⚠ %s${NC}\n" "$*"
}

# Show usage
show_usage() {
  cat << EOF
$(printf "${BLUE}ci-adm${NC}") - Eclipse Common Build Infrastructure Administration CLI

$(printf "${GREEN}Usage:${NC}")
  ci-adm <module> <command> [arguments...]
  ci-adm help [module]
  ci-adm list

$(printf "${GREEN}Available Modules:${NC}")

  $(printf "${YELLOW}github${NC}")            GitHub integration management
  $(printf "${YELLOW}gitlab${NC}")            GitLab integration management
  $(printf "${YELLOW}gpg${NC}")               GPG key and signing management
  $(printf "${YELLOW}nexus${NC}")             Nexus repository management
  $(printf "${YELLOW}pass${NC}")              Password store management
  $(printf "${YELLOW}matrix${NC}")            Matrix bot management
  $(printf "${YELLOW}sonarcloud${NC}")        SonarCloud project management
  $(printf "${YELLOW}develocity${NC}")        Develocity bot setup
  $(printf "${YELLOW}project${NC}")           Project configuration management
  $(printf "${YELLOW}gitlab-runner${NC}")     GitLab runner provisioning
  $(printf "${YELLOW}service-accounts${NC}")  Service account management
  $(printf "${YELLOW}central-sonatype${NC}")  Maven Central / Sonatype setup
  $(printf "${YELLOW}projects-storage${NC}")  Projects storage setup
  $(printf "${YELLOW}buildtools${NC}")        Build tools management

$(printf "${GREEN}Examples:${NC}")
  ci-adm github setup-bot technology.cbi
  ci-adm gpg setup-signing technology.cbi
  ci-adm gitlab create-webhook technology.cbi
  ci-adm nexus create-repos technology.cbi
  ci-adm pass add-creds technology.cbi
  ci-adm help github
  ci-adm list

$(printf "${GREEN}Get Help:${NC}")
  ci-adm help          Show this help message
  ci-adm help <module> Show help for a specific module
  ci-adm list          List all available commands

EOF
}

# Show all available commands
show_all_commands() {
  cat << EOF
$(printf "${BLUE}ci-adm${NC}") - All Available Commands

$(printf "${GREEN}GitHub Commands:${NC}")
  github setup-bot <project_name>          Setup GitHub bot for a project
  github setup-otterdog <project_name>     Setup OtterDog for a project
  github create-webhook <project_name>     Create GitHub webhook
  github deploy-key <project_name>         Setup deploy key
  github gen-credentials <project_name>    Generate GitHub credentials

$(printf "${GREEN}GitLab Commands:${NC}")
  gitlab create-bot <project_name>                 Create GitLab bot user
  gitlab create-webhook <project_name>             Create GitLab webhook
  gitlab setup-jenkins <project_name>              Setup Jenkins-GitLab integration
  gitlab setup-runner <project_name>               Setup GitLab runner integration
  gitlab setup-license-vetting <project_name>      Setup license vetting workflow
  gitlab admin <args...>                           Run GitLab admin commands

$(printf "${GREEN}GPG Commands:${NC}")
  gpg setup-signing <project_name>                 Setup GPG signing for a project
  gpg key-admin <args...>                          GPG key administration
  gpg change-passphrase <project_name>             Change GPG key passphrase

$(printf "${GREEN}Nexus Commands:${NC}")
  nexus create-repos <project_name>                Create Nexus repositories for a project

$(printf "${GREEN}Password Store Commands:${NC}")
  pass add-creds <project_name>                    Add credentials to password store
  pass add-creds-gpg <project_name>                Add GPG credentials
  pass gen-ssh-key <project_name>                  Generate SSH key
  pass change-ssh-passphrase <project_name>        Change SSH key passphrase
  pass stats                                       Show password store statistics

$(printf "${GREEN}Matrix Commands:${NC}")
  matrix setup-bot <project_name>                  Setup Matrix bot for a project
  matrix admin <args...>                           Run Matrix admin commands

$(printf "${GREEN}SonarCloud Commands:${NC}")
  sonarcloud create-project <project_name>         Create SonarCloud project
  sonarcloud create-token <project_name>           Create SonarCloud project token

$(printf "${GREEN}Develocity Commands:${NC}")
  develocity setup-bot <project_name>              Setup Develocity bot for a project

$(printf "${GREEN}Project Management Commands:${NC}")
  project check-secrets <project_name>             Check secrets structure
  project fetch-api                                Fetch projects from API
  project stats                                    Show project statistics
  project rename <old_name> <new_name>             Rename a project

$(printf "${GREEN}GitLab Runner Commands:${NC}")
  gitlab-runner provision <args...>                Provision GitLab runner (GRAC)

$(printf "${GREEN}Service Accounts Commands:${NC}")
  service-accounts setup-pypi <project_name>       Setup PyPI service account

$(printf "${GREEN}Maven Central / Sonatype Commands:${NC}")
  central-sonatype setup <project_name>            Setup Maven Central publishing

$(printf "${GREEN}Projects Storage Commands:${NC}")
  projects-storage setup <project_name>            Setup projects storage

$(printf "${GREEN}Build Tools Commands:${NC}")
  buildtools add-maven-version <version>           Add new Maven version
  buildtools check-jdk <args...>                   Check JDK configuration

EOF
}

# Show module-specific help
show_module_help() {
  local module="$1"
  
  case "$module" in
    github)
      cat << EOF
$(printf "${BLUE}ci-adm github${NC}") - GitHub integration management

$(printf "${GREEN}Commands:${NC}")
  setup-bot <project_name>         Setup GitHub bot for a project
  setup-otterdog <project_name>    Setup OtterDog for a project
  create-webhook <project_name>    Create GitHub webhook
  deploy-key <project_name>        Setup deploy key
  gen-credentials <project_name>   Generate GitHub credentials

$(printf "${GREEN}Examples:${NC}")
  ci-adm github setup-bot technology.cbi
  ci-adm github create-webhook technology.cbi
  ci-adm github deploy-key technology.cbi
EOF
      ;;
    
    gitlab)
      cat << EOF
$(printf "${BLUE}ci-adm gitlab${NC}") - GitLab integration management

$(printf "${GREEN}Commands:${NC}")
  create-bot <project_name>                Create GitLab bot user
  create-webhook <project_name>            Create GitLab webhook
  setup-jenkins <project_name>             Setup Jenkins-GitLab integration
  setup-runner <project_name>              Setup GitLab runner integration
  setup-license-vetting <project_name>     Setup license vetting workflow
  admin <args...>                          Run GitLab admin commands

$(printf "${GREEN}Examples:${NC}")
  ci-adm gitlab create-bot technology.cbi
  ci-adm gitlab create-webhook technology.cbi
  ci-adm gitlab setup-jenkins technology.cbi
EOF
      ;;
    
    gpg)
      cat << EOF
$(printf "${BLUE}ci-adm gpg${NC}") - GPG key and signing management

$(printf "${GREEN}Commands:${NC}")
  setup-signing <project_name>           Setup GPG signing for a project
  key-admin <args...>                    GPG key administration
  change-passphrase <project_name>       Change GPG key passphrase

$(printf "${GREEN}Examples:${NC}")
  ci-adm gpg setup-signing technology.cbi
  ci-adm gpg change-passphrase technology.cbi
  ci-adm gpg key-admin --help
EOF
      ;;
    
    nexus)
      cat << EOF
$(printf "${BLUE}ci-adm nexus${NC}") - Nexus repository management

$(printf "${GREEN}Commands:${NC}")
  create-repos <project_name>     Create Nexus repositories for a project

$(printf "${GREEN}Examples:${NC}")
  ci-adm nexus create-repos technology.cbi
EOF
      ;;
    
    pass)
      cat << EOF
$(printf "${BLUE}ci-adm pass${NC}") - Password store management

$(printf "${GREEN}Commands:${NC}")
  add-creds <project_name>              Add credentials to password store
  add-creds-gpg <project_name>          Add GPG credentials
  gen-ssh-key <project_name>            Generate SSH key
  change-ssh-passphrase <project_name>  Change SSH key passphrase
  stats                                 Show password store statistics

$(printf "${GREEN}Examples:${NC}")
  ci-adm pass add-creds technology.cbi
  ci-adm pass gen-ssh-key technology.cbi
  ci-adm pass stats
EOF
      ;;
    
    matrix)
      cat << EOF
$(printf "${BLUE}ci-adm matrix${NC}") - Matrix bot management

$(printf "${GREEN}Commands:${NC}")
  setup-bot <project_name>     Setup Matrix bot for a project
  admin <args...>              Run Matrix admin commands

$(printf "${GREEN}Examples:${NC}")
  ci-adm matrix setup-bot technology.cbi
  ci-adm matrix admin --help
EOF
      ;;
    
    sonarcloud)
      cat << EOF
$(printf "${BLUE}ci-adm sonarcloud${NC}") - SonarCloud project management

$(printf "${GREEN}Commands:${NC}")
  create-project <project_name>        Create SonarCloud project
  create-token <project_name>          Create SonarCloud project token

$(printf "${GREEN}Examples:${NC}")
  ci-adm sonarcloud create-project technology.cbi
  ci-adm sonarcloud create-token technology.cbi
EOF
      ;;
    
    develocity)
      cat << EOF
$(printf "${BLUE}ci-adm develocity${NC}") - Develocity bot setup

$(printf "${GREEN}Commands:${NC}")
  setup-bot <project_name>     Setup Develocity bot for a project

$(printf "${GREEN}Examples:${NC}")
  ci-adm develocity setup-bot technology.cbi
EOF
      ;;
    
    project)
      cat << EOF
$(printf "${BLUE}ci-adm project${NC}") - Project configuration management

$(printf "${GREEN}Commands:${NC}")
  check-secrets <project_name>     Check secrets structure
  fetch-api                        Fetch projects from API
  stats                            Show project statistics
  rename <old_name> <new_name>     Rename a project

$(printf "${GREEN}Examples:${NC}")
  ci-adm project check-secrets technology.cbi
  ci-adm project stats
  ci-adm project rename old.project new.project
EOF
      ;;
    
    gitlab-runner)
      cat << EOF
$(printf "${BLUE}ci-adm gitlab-runner${NC}") - GitLab runner provisioning

$(printf "${GREEN}Commands:${NC}")
  provision <args...>     Provision GitLab runner (GRAC)

$(printf "${GREEN}Examples:${NC}")
  ci-adm gitlab-runner provision --help
EOF
      ;;
    
    service-accounts)
      cat << EOF
$(printf "${BLUE}ci-adm service-accounts${NC}") - Service account management

$(printf "${GREEN}Commands:${NC}")
  setup-pypi <project_name>     Setup PyPI service account

$(printf "${GREEN}Examples:${NC}")
  ci-adm service-accounts setup-pypi technology.cbi
EOF
      ;;
    
    central-sonatype)
      cat << EOF
$(printf "${BLUE}ci-adm central-sonatype${NC}") - Maven Central / Sonatype setup

$(printf "${GREEN}Commands:${NC}")
  setup <project_name>     Setup Maven Central publishing

$(printf "${GREEN}Examples:${NC}")
  ci-adm central-sonatype setup technology.cbi
EOF
      ;;
    
    projects-storage)
      cat << EOF
$(printf "${BLUE}ci-adm projects-storage${NC}") - Projects storage setup

$(printf "${GREEN}Commands:${NC}")
  setup <project_name>     Setup projects storage

$(printf "${GREEN}Examples:${NC}")
  ci-adm projects-storage setup technology.cbi
EOF
      ;;
    
    buildtools)
      cat << EOF
$(printf "${BLUE}ci-adm buildtools${NC}") - Build tools management

$(printf "${GREEN}Commands:${NC}")
  add-maven-version <version>     Add new Maven version
  check-jdk <args...>             Check JDK configuration

$(printf "${GREEN}Examples:${NC}")
  ci-adm buildtools add-maven-version 3.9.5
  ci-adm buildtools check-jdk --help
EOF
      ;;
    
    *)
      print_error "Unknown module: $module"
      echo ""
      show_usage
      exit 1
      ;;
  esac
}

# Execute command
execute_command() {
  local module="$1"
  shift
  local command="${1:-}"
  
  if [[ -z "$command" ]]; then
    print_error "No command specified for module '$module'"
    echo ""
    show_module_help "$module"
    exit 1
  fi
  
  shift
  
  case "$module" in
    github)
      case "$command" in
        setup-bot)
          exec "${SCRIPT_DIR}/github/setup_github_bot.sh" "$@"
          ;;
        setup-otterdog)
          exec "${SCRIPT_DIR}/github/setup_otterdog.sh" "$@"
          ;;
        create-webhook)
          exec "${SCRIPT_DIR}/github/create_webhook.sh" "$@"
          ;;
        deploy-key)
          exec "${SCRIPT_DIR}/github/deploy-key.sh" "$@"
          ;;
        gen-credentials)
          exec "${SCRIPT_DIR}/github/gen-credentials.sh" "$@"
          ;;
        *)
          print_error "Unknown command for github: $command"
          echo ""
          show_module_help "github"
          exit 1
          ;;
      esac
      ;;
    
    gitlab)
      case "$command" in
        create-bot)
          exec "${SCRIPT_DIR}/gitlab/create_gitlab_bot_user.sh" "$@"
          ;;
        create-webhook)
          exec "${SCRIPT_DIR}/gitlab/create_gitlab_webhook.sh" "$@"
          ;;
        setup-jenkins)
          exec "${SCRIPT_DIR}/gitlab/setup_jenkins_gitlab_integration.sh" "$@"
          ;;
        setup-runner)
          exec "${SCRIPT_DIR}/gitlab/setup_gitlab_runner_integration.sh" "$@"
          ;;
        setup-license-vetting)
          exec "${SCRIPT_DIR}/gitlab/setup_license_vetting_workflow.sh" "$@"
          ;;
        admin)
          exec "${SCRIPT_DIR}/gitlab/gitlab_admin.sh" "$@"
          ;;
        *)
          print_error "Unknown command for gitlab: $command"
          echo ""
          show_module_help "gitlab"
          exit 1
          ;;
      esac
      ;;
    
    gpg)
      case "$command" in
        setup-signing)
          exec "${SCRIPT_DIR}/gpg/setup_gpg_signing.sh" "$@"
          ;;
        key-admin)
          exec "${SCRIPT_DIR}/gpg/gpg_key_admin.sh" "$@"
          ;;
        change-passphrase)
          exec "${SCRIPT_DIR}/gpg/change_gpg_passphrase.sh" "$@"
          ;;
        *)
          print_error "Unknown command for gpg: $command"
          echo ""
          show_module_help "gpg"
          exit 1
          ;;
      esac
      ;;
    
    nexus)
      case "$command" in
        create-repos)
          exec "${SCRIPT_DIR}/nexus/createNexusRepos.sh" "$@"
          ;;
        *)
          print_error "Unknown command for nexus: $command"
          echo ""
          show_module_help "nexus"
          exit 1
          ;;
      esac
      ;;
    
    pass)
      case "$command" in
        add-creds)
          exec "${SCRIPT_DIR}/pass/add_creds.sh" "$@"
          ;;
        add-creds-gpg)
          exec "${SCRIPT_DIR}/pass/add_creds_gpg.sh" "$@"
          ;;
        gen-ssh-key)
          exec "${SCRIPT_DIR}/pass/gen-ssh-key.sh" "$@"
          ;;
        change-ssh-passphrase)
          exec "${SCRIPT_DIR}/pass/change_SSH_passphrase.sh" "$@"
          ;;
        stats)
          exec "${SCRIPT_DIR}/pass/cbi_pass_bot_stats.sh" "$@"
          ;;
        *)
          print_error "Unknown command for pass: $command"
          echo ""
          show_module_help "pass"
          exit 1
          ;;
      esac
      ;;
    
    matrix)
      case "$command" in
        setup-bot)
          exec "${SCRIPT_DIR}/matrix/setup_matrix_bot.sh" "$@"
          ;;
        admin)
          exec "${SCRIPT_DIR}/matrix/matrix_admin.sh" "$@"
          ;;
        *)
          print_error "Unknown command for matrix: $command"
          echo ""
          show_module_help "matrix"
          exit 1
          ;;
      esac
      ;;
    
    sonarcloud)
      case "$command" in
        create-project)
          exec "${SCRIPT_DIR}/sonarcloud/create_sonarcloud_project.sh" "$@"
          ;;
        create-token)
          exec "${SCRIPT_DIR}/sonarcloud/create_sonarcloud_projects-token.sh" "$@"
          ;;
        *)
          print_error "Unknown command for sonarcloud: $command"
          echo ""
          show_module_help "sonarcloud"
          exit 1
          ;;
      esac
      ;;
    
    develocity)
      case "$command" in
        setup-bot)
          exec "${SCRIPT_DIR}/develocity/setup_develocity_bot.sh" "$@"
          ;;
        *)
          print_error "Unknown command for develocity: $command"
          echo ""
          show_module_help "develocity"
          exit 1
          ;;
      esac
      ;;
    
    project)
      case "$command" in
        check-secrets)
          exec "${SCRIPT_DIR}/project/check_secrets_structure.sh" "$@"
          ;;
        fetch-api)
          exec "${SCRIPT_DIR}/project/fetch_projects_api.sh" "$@"
          ;;
        stats)
          exec "${SCRIPT_DIR}/project/projects_stats.sh" "$@"
          ;;
        rename)
          exec "${SCRIPT_DIR}/project/rename_project.sh" "$@"
          ;;
        *)
          print_error "Unknown command for project: $command"
          echo ""
          show_module_help "project"
          exit 1
          ;;
      esac
      ;;
    
    gitlab-runner)
      case "$command" in
        provision)
          exec "${SCRIPT_DIR}/gitlab-runner/grac_provisionning.sh" "$@"
          ;;
        *)
          print_error "Unknown command for gitlab-runner: $command"
          echo ""
          show_module_help "gitlab-runner"
          exit 1
          ;;
      esac
      ;;
    
    service-accounts)
      case "$command" in
        setup-pypi)
          exec "${SCRIPT_DIR}/service-accounts/setup_pypi_account.sh" "$@"
          ;;
        *)
          print_error "Unknown command for service-accounts: $command"
          echo ""
          show_module_help "service-accounts"
          exit 1
          ;;
      esac
      ;;
    
    central-sonatype)
      case "$command" in
        setup)
          exec "${SCRIPT_DIR}/central_sonatype/setup_central_sonatype.sh" "$@"
          ;;
        *)
          print_error "Unknown command for central-sonatype: $command"
          echo ""
          show_module_help "central-sonatype"
          exit 1
          ;;
      esac
      ;;
    
    projects-storage)
      case "$command" in
        setup)
          exec "${SCRIPT_DIR}/projects-storage/setup_projects_storage.sh" "$@"
          ;;
        *)
          print_error "Unknown command for projects-storage: $command"
          echo ""
          show_module_help "projects-storage"
          exit 1
          ;;
      esac
      ;;
    
    buildtools)
      case "$command" in
        add-maven-version)
          exec "${SCRIPT_DIR}/buildtools/addNewMavenVersion.sh" "$@"
          ;;
        check-jdk)
          exec "${SCRIPT_DIR}/buildtools/check_jdk.sh" "$@"
          ;;
        *)
          print_error "Unknown command for buildtools: $command"
          echo ""
          show_module_help "buildtools"
          exit 1
          ;;
      esac
      ;;
    
    *)
      print_error "Unknown module: $module"
      echo ""
      show_usage
      exit 1
      ;;
  esac
}

# Main
main() {
  if [[ $# -eq 0 ]]; then
    show_usage
    exit 0
  fi
  
  case "$1" in
    help|-h|--help)
      if [[ $# -gt 1 ]]; then
        show_module_help "$2"
      else
        show_usage
      fi
      exit 0
      ;;
    
    list|-l|--list)
      show_all_commands
      exit 0
      ;;
    
    *)
      execute_command "$@"
      ;;
  esac
}

main "$@"
