#!/usr/bin/env bash

#*******************************************************************************
# Copyright (c) 2026 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html
# SPDX-License-Identifier: EPL-2.0
#*******************************************************************************
# // Some portions generated by Co-Pilot

# Usage:
#   ./repo_size.sh <REPO> [NEXUS_HOST]
#   ./repo_size.sh <REPO> <NEXUS_TOKEN_USERNAME> <NEXUS_TOKEN_PASSWORD> [NEXUS_HOST]
# If credentials are not provided as args, fallback to:
#   NEXUS_TOKEN_USERNAME and NEXUS_TOKEN_PASSWORD

set -euo pipefail

SCRIPT_NAME=$(basename "$0")
DEBUG="${DEBUG:-0}"
API_CALL_COUNT=0

usage() {
  echo "Usage:" >&2
  echo "  $SCRIPT_NAME [--debug|-d] <REPO> [NEXUS_HOST]" >&2
  echo "  $SCRIPT_NAME [--debug|-d] <REPO> <NEXUS_TOKEN_USERNAME> <NEXUS_TOKEN_PASSWORD> [NEXUS_HOST]" >&2
  echo "Credentials fallback env vars: NEXUS_TOKEN_USERNAME / NEXUS_TOKEN_PASSWORD" >&2
  echo "Debug mode: --debug (or DEBUG=1)" >&2
}

urlencode() {
  jq -rn --arg v "${1:-}" '$v|@uri'
}

debug_log() {
  if [[ "$DEBUG" == "1" ]]; then
    echo "[DEBUG] $*" >&2
  fi
}

bytes_to_human() {
  local bytes="${1:-0}"
  awk -v b="$bytes" '
    function human(x) {
      split("B KiB MiB GiB TiB PiB", u, " ")
      i = 1
      while (x >= 1024 && i < length(u)) {
        x /= 1024
        i++
      }
      if (i == 1) return sprintf("%d %s", x, u[i])
      return sprintf("%.2f %s", x, u[i])
    }
    BEGIN { print human(b + 0) }
  '
}

test_credentials() {
  local base_url="https://$NEXUS_HOST"
  local status_url="$base_url/service/rest/v1/status"
  local repos_url="$base_url/service/rest/v1/repositories"
  local repo_probe_url="$base_url/service/rest/v1/assets?repository=$(urlencode "$REPO")"
  local status

  # 1) Reachability probe (no auth)
  API_CALL_COUNT=$((API_CALL_COUNT + 1))
  status=$(curl -sS -o /dev/null -w "%{http_code}" "$status_url" || true)
  if [[ "$status" == "000" ]]; then
    echo "[ERROR] Nexus host unreachable: $NEXUS_HOST" >&2
    exit 2
  fi

  # 2) Auth probe
  status=$(curl -sS -o /dev/null -w "%{http_code}" -u "$NEXUS_TOKEN_USERNAME:$NEXUS_TOKEN_PASSWORD" "$repos_url" || true)
  if [[ "$status" != "200" ]]; then
    echo "[ERROR] Authentication failed on $repos_url (HTTP $status)." >&2
    echo "[HINT] Try: ./repo_size.sh \"$REPO\" '$NEXUS_TOKEN_USERNAME' '<NEXUS_TOKEN_PASSWORD>' '$NEXUS_HOST'" >&2
    exit 2
  fi

  # 3) Repository-level access probe
  status=$(curl -sS -o /dev/null -w "%{http_code}" -u "$NEXUS_TOKEN_USERNAME:$NEXUS_TOKEN_PASSWORD" "$repo_probe_url" || true)
  if [[ "$status" == "403" ]]; then
    echo "[ERROR] Authenticated but forbidden to read repository '$REPO' (HTTP 403)." >&2
    exit 2
  fi
  if [[ "$status" == "404" ]]; then
    echo "[ERROR] Repository '$REPO' not found (HTTP 404)." >&2
    exit 2
  fi

  debug_log "Reachability status: $status_url => reachable"
  debug_log "Auth probe       : $repos_url => 200"
  debug_log "Repo probe       : $repo_probe_url => $status"
}

fetch_assets() {
  local tmp_json="$1"
  local token=""
  local page=1
  local total_items=0

  : > "$tmp_json"

  echo "[INFO] Fetching assets from Nexus repository '$REPO' on '$NEXUS_HOST'..." >&2

  while :; do
    local url="https://$NEXUS_HOST/service/rest/v1/assets?repository=$(urlencode "$REPO")"
    [[ -n "$token" ]] && url+="&continuationToken=$(urlencode "$token")"

    local response
    local page_items
    local has_next_token="no"
    debug_log "Fetching page=$page (next_api_call=$((API_CALL_COUNT + 1)))"
    API_CALL_COUNT=$((API_CALL_COUNT + 1))
    response=$(curl -sS -u "$NEXUS_TOKEN_USERNAME:$NEXUS_TOKEN_PASSWORD" "$url")

    if ! echo "$response" | jq -e . >/dev/null 2>&1; then
      echo "[ERROR] Invalid JSON response from Nexus (page $page)." >&2
      exit 3
    fi

    page_items=$(echo "$response" | jq '.items | length')
    total_items=$((total_items + page_items))

    # Keep only lines with a path and a numeric fileSize.
    echo "$response" | jq -c '.items[]? | select(.path != null and .fileSize != null) | {path: .path, size: (.fileSize | tonumber)}' >> "$tmp_json"

    token=$(echo "$response" | jq -r '.continuationToken // empty')
    [[ -n "$token" ]] && has_next_token="yes"
    debug_log "Progress: page=$page page_items=$page_items total_items=$total_items has_next_token=$has_next_token api_calls=$API_CALL_COUNT"
    [[ -z "$token" ]] && break

    page=$((page + 1))
  done

  debug_log "Fetch completed: pages=$page total_items=$total_items api_calls=$API_CALL_COUNT"
}

build_report() {
  local tmp_json="$1"
  local tmp_agg
  local tmp_files
  local total_bytes
  local total_files
  local unique_paths

  tmp_agg=$(mktemp)
  tmp_files=$(mktemp)

  jq -r '[.size, .path] | @tsv' "$tmp_json" > "$tmp_files"

  total_bytes=$(awk -F'\t' '{sum += $1} END {print sum + 0}' "$tmp_files")
  total_files=$(wc -l < "$tmp_files" | tr -d ' ')
  unique_paths=$(awk -F'\t' '{print $2}' "$tmp_files" | sort -u | wc -l | tr -d ' ')

  awk -F'\t' '
    {
      size=$1
      path=$2

      # Mark the file itself as an artifact
      filePaths[path] = size

      n = split(path, p, "/")
      # Build directory hierarchy (excluding the file itself)
      for (i=1; i<n; i++) {
        if (i == 1) {
          key = "/" p[1]
        } else {
          key = key "/" p[i]
        }
        dirSizes[key] += size
      }

      split(path, extParts, ".")
      if (length(extParts) > 1) {
        ext = tolower(extParts[length(extParts)])
      } else {
        ext = "(no_ext)"
      }
      extSizes[ext] += size
      extCounts[ext] += 1
    }
    END {
      for (k in dirSizes) {
        printf("DIR\t%d\t%s\n", dirSizes[k], k)
      }
      for (f in filePaths) {
        printf("FILE\t%d\t%s\n", filePaths[f], f)
      }
      for (e in extSizes) {
        printf("EXT\t%d\t%d\t%s\n", extSizes[e], extCounts[e], e)
      }
    }
  ' "$tmp_files" | sort -t $'\t' -k1,1 -k2,2nr > "$tmp_agg"

  {
    echo "===== Repository Size Report ====="
    echo "Repository : $REPO"
    echo "Nexus host : $NEXUS_HOST"
    echo "Generated  : $(date '+%Y-%m-%d %H:%M:%S %Z')"
    echo
    echo "Global summary"
    echo "- API calls           : $API_CALL_COUNT"
    echo "- Total files         : $total_files"
    echo "- Unique asset paths  : $unique_paths"
    echo "- Total size          : $(bytes_to_human "$total_bytes") ($total_bytes bytes)"
    echo
    echo "Top 20 directories by size"
    awk -F'\t' '$1=="DIR" {print $2"\t"$3}' "$tmp_agg" | head -n 20 | while IFS=$'\t' read -r b p; do
      printf -- "- %-12s %s\n" "$(bytes_to_human "$b")" "$p"
    done
    echo
    echo "Top 20 artifacts by size"
    awk -F'\t' '$1=="FILE" {print $2"\t"$3}' "$tmp_agg" | head -n 20 | while IFS=$'\t' read -r b p; do
      printf -- "- %-12s %s\n" "$(bytes_to_human "$b")" "$p"
    done
    echo
    echo "Top 10 extensions by total size"
    awk -F'\t' '$1=="EXT" {print $2"\t"$3"\t"$4}' "$tmp_agg" | head -n 10 | while IFS=$'\t' read -r b c e; do
      printf -- "- %-8s %-12s %s\n" "$e" "$(bytes_to_human "$b")" "$c files"
    done
    echo "===== End of Report ====="
  }

  rm -f "$tmp_agg" "$tmp_files"
}

main() {
  local -a args=()
  local arg
  for arg in "$@"; do
    case "$arg" in
      --debug|-d)
        DEBUG=1
        ;;
      *)
        args+=("$arg")
        ;;
    esac
  done
  set -- "${args[@]}"

  if [[ $# -lt 1 || $# -gt 4 ]]; then
    usage
    exit 1
  fi

  REPO="$1"
  NEXUS_HOST="${NEXUS_HOST:-repo.eclipse.org}"
  NEXUS_TOKEN_USERNAME="${NEXUS_TOKEN_USERNAME:-}"
  NEXUS_TOKEN_PASSWORD="${NEXUS_TOKEN_PASSWORD:-}"

  case $# in
    1)
      :
      ;;
    2)
      NEXUS_HOST="$2"
      :
      ;;
    3)
      NEXUS_TOKEN_USERNAME="$2"
      NEXUS_TOKEN_PASSWORD="$3"
      ;;
    4)
      NEXUS_TOKEN_USERNAME="$2"
      NEXUS_TOKEN_PASSWORD="$3"
      NEXUS_HOST="$4"
      ;;
  esac

  if [[ -z "$NEXUS_TOKEN_USERNAME" || -z "$NEXUS_TOKEN_PASSWORD" ]]; then
    echo "[ERROR] Missing Nexus credentials." >&2
    echo "[HINT] Pass credentials as arguments, or set NEXUS_TOKEN_USERNAME and NEXUS_TOKEN_PASSWORD." >&2
    usage
    exit 1
  fi

  local tmp_json
  tmp_json=$(mktemp)
  trap 'rm -f "$tmp_json"' EXIT

  test_credentials
  fetch_assets "$tmp_json"
  build_report "$tmp_json"
}

main "$@"
